In [1]:
import weather_class
import pandas as pd

In [2]:
atl_url = weather_class.stadiums_dict['ATL']

In [3]:
weather_dfs = pd.read_html(atl_url, header=None, index_col = None)
stadium_weather_df = weather_dfs[7].copy()
del weather_dfs

In [4]:
stadium_weather_df

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Date,08/27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08/28
2,Hour (EDT),01,02,03,04,05,06,07,08,09,...,15,16,17,18,19,20,21,22,23,00
3,Temperature (°F),74,73,73,72,72,72,72,73,76,...,89,89,88,87,85,83,81,80,78,78
4,Dewpoint (°F),73,73,72,72,71,71,72,72,73,...,74,73,73,73,73,73,73,73,72,72
5,Heat Index (°F),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76,...,98,97,96,94,92,89,86,83,78,78
6,Surface Wind (mph),0,0,0,0,0,1,1,2,3,...,7,7,7,6,6,5,5,5,5,5
7,Wind Dir,E,E,SE,SE,SE,SE,SE,SE,SE,...,S,S,S,S,S,S,S,S,S,S
8,Gust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Sky Cover (%),49,49,50,50,50,50,50,55,54,...,53,59,62,64,69,71,73,78,80,80
10,Precipitation Potential (%),14,11,8,6,4,5,6,7,8,...,17,17,17,16,14,12,11,10,8,8
11,Relative Humidity (%),97,97,97,97,97,97,98,98,92,...,61,60,61,64,68,73,76,79,81,82
12,Rain,--,--,--,--,--,--,--,--,--,...,SChc,SChc,SChc,SChc,--,--,--,--,--,--
13,Thunder,--,--,--,--,--,--,--,--,--,...,SChc,SChc,SChc,SChc,--,--,--,--,--,--
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08/29
16,Hour (EDT),01,02,03,04,05,06,07,08,09,...,15,16,17,18,19,20,21,22,23,00
17,Temperature (°F),77,77,76,76,75,75,74,74,76,...,87,87,86,84,82,80,78,76,75,75
18,Dewpoint (°F),72,71,71,71,71,72,72,72,73,...,76,75,75,75,75,76,75,74,74,74
19,Heat Index (°F),77,77,76,76,75,75,NaN,NaN,76,...,98,97,95,93,89,84,78,76,75,75
20,Surface Wind (mph),5,5,5,5,5,5,5,5,5,...,9,9,9,9,8,7,6,6,6,6
21,Wind Dir,S,S,S,S,S,S,S,S,S,...,SW,SW,SW,SW,S,S,SW,S,S,S
22,Gust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15,15,15,15,NaN,NaN,NaN,NaN,NaN,NaN
23,Sky Cover (%),79,79,79,79,79,77,74,72,73,...,75,78,79,80,83,84,87,87,87,87
24,Precipitation Potential (%),7,6,5,5,6,7,9,27,27,...,48,48,48,48,48,38,38,38,38,38
25,Relative Humidity (%),83,83,85,86,88,90,92,94,92,...,68,68,70,74,81,88,92,94,96,97
26,Rain,--,--,--,--,--,--,--,Chc,Chc,...,Chc,Chc,Chc,Chc,Chc,Chc,Chc,Chc,Chc,Chc
27,Thunder,--,--,--,--,--,--,--,Chc,Chc,...,Chc,Chc,Chc,Chc,Chc,Chc,Chc,Chc,Chc,Chc

In [5]:
# Find rows to transpose
stadium_weather_df.insert(0, 'row_num', range(0,len(stadium_weather_df))) # add row_num
rows_to_copy = stadium_weather_df[['row_num']][stadium_weather_df[0] == 'Date'].copy()
rows_to_copy = rows_to_copy.reset_index().drop(['index'], axis=1)
rows_to_copy['row_num'][1] = rows_to_copy['row_num'][1]-2

In [7]:
stadium_weather_df

,row_num,0,1,2,3,4,5,6,7,8,...,15,16,17,18,19,20,21,22,23,24
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Date,08/27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08/28
2,2,Hour (EDT),01,02,03,04,05,06,07,08,...,15,16,17,18,19,20,21,22,23,00
3,3,Temperature (°F),74,73,73,72,72,72,72,73,...,89,89,88,87,85,83,81,80,78,78
4,4,Dewpoint (°F),73,73,72,72,71,71,72,72,...,74,73,73,73,73,73,73,73,72,72
5,5,Heat Index (°F),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98,97,96,94,92,89,86,83,78,78
6,6,Surface Wind (mph),0,0,0,0,0,1,1,2,...,7,7,7,6,6,5,5,5,5,5
7,7,Wind Dir,E,E,SE,SE,SE,SE,SE,SE,...,S,S,S,S,S,S,S,S,S,S
8,8,Gust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,Sky Cover (%),49,49,50,50,50,50,50,55,...,53,59,62,64,69,71,73,78,80,80
10,10,Precipitation Potential (%),14,11,8,6,4,5,6,7,...,17,17,17,16,14,12,11,10,8,8
11,11,Relative Humidity (%),97,97,97,97,97,97,98,98,...,61,60,61,64,68,73,76,79,81,82
12,12,Rain,--,--,--,--,--,--,--,--,...,SChc,SChc,SChc,SChc,--,--,--,--,--,--
13,13,Thunder,--,--,--,--,--,--,--,--,...,SChc,SChc,SChc,SChc,--,--,--,--,--,--
14,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08/29
16,16,Hour (EDT),01,02,03,04,05,06,07,08,...,15,16,17,18,19,20,21,22,23,00
17,17,Temperature (°F),77,77,76,76,75,75,74,74,...,87,87,86,84,82,80,78,76,75,75
18,18,Dewpoint (°F),72,71,71,71,71,72,72,72,...,76,75,75,75,75,76,75,74,74,74
19,19,Heat Index (°F),77,77,76,76,75,75,NaN,NaN,...,98,97,95,93,89,84,78,76,75,75
20,20,Surface Wind (mph),5,5,5,5,5,5,5,5,...,9,9,9,9,8,7,6,6,6,6
21,21,Wind Dir,S,S,S,S,S,S,S,S,...,SW,SW,SW,SW,S,S,SW,S,S,S
22,22,Gust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15,15,15,15,NaN,NaN,NaN,NaN,NaN,NaN
23,23,Sky Cover (%),79,79,79,79,79,77,74,72,...,75,78,79,80,83,84,87,87,87,87
24,24,Precipitation Potential (%),7,6,5,5,6,7,9,27,...,48,48,48,48,48,38,38,38,38,38
25,25,Relative Humidity (%),83,83,85,86,88,90,92,94,...,68,68,70,74,81,88,92,94,96,97
26,26,Rain,--,--,--,--,--,--,--,Chc,...,Chc,Chc,Chc,Chc,Chc,Chc,Chc,Chc,Chc,Chc
27,27,Thunder,--,--,--,--,--,--,--,Chc,...,Chc,Chc,Chc,Chc,Chc,Chc,Chc,Chc,Chc,Chc

In [6]:
rows_to_copy

   row_num
0        1
1       13

In [8]:
# Drop row_num
stadium_weather_df = stadium_weather_df.drop('row_num', axis=1)

In [9]:
# transpose the dataframe
stadium_weather_copy_df = stadium_weather_df.loc[rows_to_copy['row_num'][0]:rows_to_copy['row_num'][1], :].T.copy()
del stadium_weather_df

In [10]:
# Create Propper Header
stadium_weather_copy_df = stadium_weather_copy_df.rename(columns=stadium_weather_copy_df.iloc[0])

In [11]:
# Drop Redundant first row
stadium_weather_copy_df = stadium_weather_copy_df.drop([0])

In [12]:
stadium_weather_copy_df

,Date,Hour (EDT),Temperature (°F),Dewpoint (°F),Heat Index (°F),Surface Wind (mph),Wind Dir,Gust,Sky Cover (%),Precipitation Potential (%),Relative Humidity (%),Rain,Thunder
1,08/27,01,74,73,NaN,0,E,NaN,49,14,97,--,--
2,NaN,02,73,73,NaN,0,E,NaN,49,11,97,--,--
3,NaN,03,73,72,NaN,0,SE,NaN,50,8,97,--,--
4,NaN,04,72,72,NaN,0,SE,NaN,50,6,97,--,--
5,NaN,05,72,71,NaN,0,SE,NaN,50,4,97,--,--
6,NaN,06,72,71,NaN,1,SE,NaN,50,5,97,--,--
7,NaN,07,72,72,NaN,1,SE,NaN,50,6,98,--,--
8,NaN,08,73,72,NaN,2,SE,NaN,55,7,98,--,--
9,NaN,09,76,73,76,3,SE,NaN,54,8,92,--,--
10,NaN,10,79,75,83,3,S,NaN,52,9,86,--,--
11,NaN,11,82,75,89,5,S,NaN,51,8,80,--,--
12,NaN,12,84,75,93,5,S,NaN,50,8,74,--,--
13,NaN,13,87,75,96,6,S,NaN,50,12,68,--,--
14,NaN,14,88,74,97,6,S,NaN,50,18,64,SChc,SChc
15,NaN,15,89,74,98,7,S,NaN,53,17,61,SChc,SChc
16,NaN,16,89,73,97,7,S,NaN,59,17,60,SChc,SChc
17,NaN,17,88,73,96,7,S,NaN,62,17,61,SChc,SChc
18,NaN,18,87,73,94,6,S,NaN,64,16,64,SChc,SChc
19,NaN,19,85,73,92,6,S,NaN,69,14,68,--,--
20,NaN,20,83,73,89,5,S,NaN,71,12,73,--,--
21,NaN,21,81,73,86,5,S,NaN,73,11,76,--,--
22,NaN,22,80,73,83,5,S,NaN,78,10,79,--,--
23,NaN,23,78,72,78,5,S,NaN,80,8,81,--,--
24,08/28,00,78,72,78,5,S,NaN,80,8,82,--,--

In [13]:
# Replace NaN in Date
## Get Dates
dates_df = pd.DataFrame(columns=['Date'])
for i in stadium_weather_copy_df['Date']:
    if type(i) == str:
        SR_row = pd.Series({'Date' : i})
        dates_df = dates_df.append(SR_row,ignore_index=True)

In [14]:
dates_df

    Date
0  08/27
1  08/28

In [17]:
SR_row

Date    08/28
dtype: object

In [15]:
## Get Row Numbers of NaN
date_row_num = pd.DataFrame(columns=['row_num'])

In [16]:
date_row_num

Empty DataFrame
Columns: [row_num]
Index: []

In [18]:
for i in range(1,len(stadium_weather_copy_df['Date'])):
    if type(stadium_weather_copy_df['Date'][i]) == str:
        SR_row = pd.Series({'row_num' : i})
        date_row_num = date_row_num.append(SR_row,ignore_index=True)
date_row_num = date_row_num.append(pd.Series({'row_num' : len(stadium_weather_copy_df['Date'])}),ignore_index=True)

In [19]:
date_row_num

  row_num
0       1
1      24

In [28]:
for i in range(1,(len(dates_df)+1)):
    if i == 1:
        stadium_weather_copy_df['Date'][(date_row_num['row_num'][1-1]-1):date_row_num['row_num'][1]].fillna(dates_df['Date'][i-1], inplace = True)
    if i == 2:
        if date_row_num['row_num'][1] != 24:
            stadium_weather_copy_df['Date'][date_row_num['row_num'][(2-1)]:date_row_num['row_num'][2]].fillna(dates_df['Date'][i-1], inplace = True)


stadium_weather_copy_df

,Date,Hour (EDT),Temperature (°F),Dewpoint (°F),Heat Index (°F),Surface Wind (mph),Wind Dir,Gust,Sky Cover (%),Precipitation Potential (%),Relative Humidity (%),Rain,Thunder
1,08/27,01,74,73,NaN,0,E,NaN,49,14,97,--,--
2,08/27,02,73,73,NaN,0,E,NaN,49,11,97,--,--
3,08/27,03,73,72,NaN,0,SE,NaN,50,8,97,--,--
4,08/27,04,72,72,NaN,0,SE,NaN,50,6,97,--,--
5,08/27,05,72,71,NaN,0,SE,NaN,50,4,97,--,--
6,08/27,06,72,71,NaN,1,SE,NaN,50,5,97,--,--
7,08/27,07,72,72,NaN,1,SE,NaN,50,6,98,--,--
8,08/27,08,73,72,NaN,2,SE,NaN,55,7,98,--,--
9,08/27,09,76,73,76,3,SE,NaN,54,8,92,--,--
10,08/27,10,79,75,83,3,S,NaN,52,9,86,--,--
11,08/27,11,82,75,89,5,S,NaN,51,8,80,--,--
12,08/27,12,84,75,93,5,S,NaN,50,8,74,--,--
13,08/27,13,87,75,96,6,S,NaN,50,12,68,--,--
14,08/27,14,88,74,97,6,S,NaN,50,18,64,SChc,SChc
15,08/27,15,89,74,98,7,S,NaN,53,17,61,SChc,SChc
16,08/27,16,89,73,97,7,S,NaN,59,17,60,SChc,SChc
17,08/27,17,88,73,96,7,S,NaN,62,17,61,SChc,SChc
18,08/27,18,87,73,94,6,S,NaN,64,16,64,SChc,SChc
19,08/27,19,85,73,92,6,S,NaN,69,14,68,--,--
20,08/27,20,83,73,89,5,S,NaN,71,12,73,--,--
21,08/27,21,81,73,86,5,S,NaN,73,11,76,--,--
22,08/27,22,80,73,83,5,S,NaN,78,10,79,--,--
23,08/27,23,78,72,78,5,S,NaN,80,8,81,--,--
24,08/28,00,78,72,78,5,S,NaN,80,8,82,--,--

In [23]:
date_row_num['row_num'][1-1]-1

0

In [25]:
date_row_num['row_num'][1]

24

In [21]:
for i in range(1,(len(dates_df)+1)):
    print(i)

1
2

In [ ]:
# Replace other NaN with '--'
stadium_weather_copy_df.fillna('--', inplace = True)

In [ ]:
# Remove the degrees sign
keys = ['Date', 'Hour (CDT)', 'Temperature (°F)', 'Dewpoint (°F)', 'Wind Chill (°F)', 'Surface Wind (mph)',
        'Wind Dir', 'Gust', 'Sky Cover (%)', 'Precipitation Potential (%)', 'Relative Humidity (%)',
        'Rain', 'Thunder', 'Snow', 'Freezing Rain', 'Sleet']
values = ['Date', 'Hour (CDT)', 'Temperature (F)', 'Dewpoint (F)', 'Wind Chill (F)', 'Surface Wind (mph)', 'Wind Dir',
        'Gust', 'Sky Cover (pct)', 'Precipitation Potential (pct)', 'Relative Humidity (pct)', 'Rain', 'Thunder',
        'Snow', 'Freezing Rain', 'Sleet']
dictionary = dict(zip(keys, values))
stadium_weather_copy_df = stadium_weather_copy_df.rename(columns=dictionary)
stadium_weather_copy_df.insert(0, 'Team', self.team_abbr)

In [ ]:
return(stadium_weather_copy_df)